variables:
- group: "production"

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - poc-csharp

pool:
  vmImage: ubuntu-latest

jobs:
- job: CI
  steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'
    displayName: 'Install .NET SDK'
  - bash: |
      cd poc-csharp
      dotnet restore
      dotnet build --configuration Release --no-restore
      dotnet publish --configuration Release --no-build --output $(Pipeline.Workspace)/publish
    displayName: 'Build and publish'
  - task: DownloadSecureFile@1
    name: userPromptTxt
    displayName: 'Download user-prompt.txt'
    inputs:
      secureFile: 'user-prompt.txt'
  - task: DownloadSecureFile@1
    name: systemPromptTxt
    displayName: 'Download system-prompt.txt'
    inputs:
      secureFile: 'system-prompt.txt'
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo Installing $(userPromptTxt.secureFilePath) to build directory
        cp $(userPromptTxt.secureFilePath) $(Pipeline.Workspace)/publish/resources/user-prompt.txt
        echo Installing $(systemPromptTxt.secureFilePath) to build directory
        cp $(systemPromptTxt.secureFilePath) $(Pipeline.Workspace)/publish/resources/system-prompt.txt
    displayName: 'Install prompt files'
  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: '$(Pipeline.Workspace)/publish'
      includeRootFolder: false
      archiveFile: '$(System.ArtifactStagingDirectory)/build$(Build.BuildId).zip'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.ArtifactStagingDirectory)/build$(Build.BuildId).zip'
      publishLocation: 'pipeline'
      artifact: 'poc-csharp'

- deployment: CD
  dependsOn: CI
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  environment: 'Azure'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureFunctionApp@2
          inputs:
            connectedServiceNameARM: '$(azureSubscription)'
            appType: 'functionAppLinux'
            appName: '$(functionAppName)'
            package: '$(Pipeline.Workspace)/poc-csharp/*.zip'
            runtimeStack: 'DOTNET-ISOLATED|8.0'
